config/routes.rb
Rails.application.routes.draw do

  resources :send_loves
  resources :talks

  root 'static_pages#home'
  get '/about' => 'static_pages#show', page: 'about'
  get '/branch_new_page' => 'static_pages#show', page: 'brand_new_page'

end

app/models/send_love.rb
class SendLove < ActiveRecord::Base
end

app/models/talk.rb
class Talk < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/send_loves_controller.rb
class SendLovesController < ApplicationController

  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  def index
    @send_loves = SendLove.all
  end

  def new
    @send_love = SendLove.new
  end

  def create
    @send_love = SendLove.new(send_love_params)

    respond_to do |format|
      if @send_love.save
        format.html { redirect_to @send_love, notice: 'Send Love was successfully created.' }
        format.json { render :show, status: :created, location: @send_love }
      else
        format.html { render :new }
        format.json { render json: @send_love.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @send_love.update(send_love_params)
        format.html { redirect_to @send_love, notice: 'Send Love was successfully updated.' }
        format.json { render :show, status: :ok, location: @send_love }
      else
        format.html { render :edit }
        format.json { render json: @send_love.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_garden
    @send_love = SendLove.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def send_love_params
    params.require(:send_love).permit(:email)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    render template: "static_pages/#{params[:page]}"
  end

end

app/controllers/talks_controller.rb
#
# Copyright (c) 2013 President and Fellows of Harvard College. All rights
# reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice, this list
# of conditions and the following disclaimer.
# Redistributions in binary form must reproduce the above copyright notice, this
# list of conditions and the following disclaimer in the documentation and/or
# other materials provided with the distribution. Neither the name "Harvard" nor
# the names of its contributors may be used to endorse or promote products derived
# from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
# OF SUCH DAMAGE.
#


class TalksController < ApplicationController

  before_action :set_talk, only: [:show, :edit, :update, :destroy]

  def index
    @talks = Talk.all
  end

  def new
    @talk = Talk.new
  end

  def create
    @talk = Talk.new(talk_params)

    respond_to do |format|
      if @talk.save
        format.html { redirect_to root_path} #, notice: 'YOUR MESSAGE GOES HERE'
        format.json { render :show, status: :created, location: @talk }
      else
        format.html { render :new }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @talk.update(talk_params)
        format.html { redirect_to root_path } #, notice: 'YOUR MESSAGE GOES HERE'
        format.json { render :show, status: :ok, location: @talk }
      else
        format.html { render :edit }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_talk
    @talk = Talk.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def talk_params
    params.require(:talk).permit(:email, :message)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Calabacitas
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = csrf_meta_tags

%body
  = yield

app/views/send_loves/_form.html.haml
= form_for @send_love do |form|
  - if @send_love.errors.any?
    #error_explanation
      %h2= "#{pluralize(@send_love.errors.count, "error")} prohibited this garden from being saved:"
      %ul
        - @send_love.errors.full_messages.each do |message|
          %li= message

  .field
    = form.label :email
    = form.text_field :email

  = form.submit 'Send Love'

app/views/send_loves/index.html.haml
%h1 Love Senders

%table
  %thead
    %tr
      %th Email
      %th Actions

  %tbody
    - @send_loves.each do |love|
      %tr
        %td= love.email
        %td= link_to 'Show', love
        %td= link_to 'Edit', edit_send_lofe_path(love)
        %td= link_to 'Destroy', love, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'Send Love', new_send_lofe_path

app/views/send_loves/new.html.haml
%h2 Talk to Us

= render 'form'

= link_to 'Back', send_loves_path

app/views/send_loves/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @send_love.email

= link_to 'Edit', edit_send_lofe_path(@send_love)
\|
= link_to 'Back', send_loves_path

app/views/static_pages/about.html.haml
%h2 Somos las calabazas

%ul
  %li
    = link_to 'Home', root_path

app/views/static_pages/brand_new_page.html.haml
#brand-new-page
  %h1 USER CUSTOMIZED TEXT

  .blurb
    USER CUSTOMIZED BLURB

app/views/static_pages/home.html.haml
#home
  /center
  %h1 Oh My Gherkin Live!

  - if notice
    #notice
      = notice

  .navigation
    %ul
      %li
        = link_to 'About Us', about_path, id: 'about-us'
      %li
        = link_to 'Talk to Us', new_talk_path, id: 'talk-to-us'
      /
        %li
          = link_to 'Brand New Page', about_path, id: 'brand-new-page'
  #video
    .heading-text
      USER CUSTOMIZED
    .link
      %iframe{src: 'https://www.youtube.com/embed/EkEjTLcK3CU', width: '560', height: '315', frameborder: '0'}

app/views/talks/_form.html.haml
= form_for @talk do |form|
  - if @talk.errors.any?
    #error_explanation
      %h2= "#{pluralize(@talk.errors.count, 'error')} prohibited this form from being saved:"
      %ul
        - @talk.errors.full_messages.each do |message|
          %li= message

  .field
    = form.label :email
    = form.text_field :email

  .field
    = form.label :message
    = form.text_area :message

  = link_to 'Cancel', root_path
  = form.submit 'Send Love'

app/views/talks/edit.html.haml
%h1 Talk to Us

= render 'form'

app/views/talks/index.html.haml
%h1 Talk to Us List

%table
  %thead
    %tr
      %th Email
      %th Actions

  %tbody
    - @talks.each do |talk|
      %tr
        %td= talk.email
        %td= talk.message
        %td= link_to 'Show', talk
        %td= link_to 'Edit', edit_talk_path(talk)
        %td= link_to 'Destroy', talk, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'Talk to Us', new_talk_path

app/views/talks/new.html.haml
%h1 Talk to Us

= render 'form'

app/views/talks/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @talk.email
%p
  %b Message:
  = @talk.message

= link_to 'Edit', edit_talk_path(@talk)
\|
= link_to 'Back', talks_path